GIT_AUTHOR_NAME="Scott Hall"
GIT_AUTHOR_EMAIL="scott@codezoom.com"
GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
DIGITALOCEAN_ACCESS_TOKEN=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
