---

#   ^#\s+(.*?)\ndefaults write (\S+)\s+(\S+)\s+-(\S+)\s(.*?)$
#   - domain: $2\n  key: $3\n  type: $4\n  value: $5\n  name: $1\n

# TODO
# GPG keys (backup, restore, replace, promote)
# VSCode extenions and config
# Create files from file templates in roles
  # - DEV_CLI
  #   * Zsh (/etc as well as homedir, plus imports)
  #   * Tmux
  #   * Tmuxinator
  #   * htop
  #   * xterm
  #   * Zshplugs should get it's own playbook/tags
  #   * Ghostty
  #   * Noba/nccm (generate from hosts in other Ansible?)
  # - DEV_TOOLS
  #   * awesome print (aprc)
  #   * curl
  #   * fontforge
  #   * gdb
  #   * git (global ignore and config)
  #   * irb
  #   * multitail
  #   * npm
  #   * psql
  #   * readline
  #   * wget
  # - DOCKER
  # - NEOVIM
  #   * vim config
  #   * git pull of plug.vim
  #   * plugins.vim
# Move Alfred Preferences into iCloud?
# ASDF 
# PyEnv
# Karabiner config into macos role/pb
# Have a host rename task
  # - The idea is inventory will be all my Macs and possibly linux systems once I expand to that.
  # - When setting up a new Mac I can use an existing Mac to run the Ansible, or I should have a 
  # - bootloader script to get the bare minimum installed to load the Ansible repo.
# Setup scripts and do aliases automatically so I don't need to type extension
# Close apps affected by default changes https://stackoverflow.com/questions/43961903/registering-multiple-variables-in-a-loop
# update ssh/gpg keys (seperate playbook?)
# Make template for ~/.ssh/config (part of the above?)
# Task to add Ansible Vault key to keychain
# Add an SSH tmux config to change status BAR for remote sessions (location and styling)
# TMUX persistance
  # https://github.com/tmux-plugins/tmux-resurrect/blob/master/README.md
  # https://github.com/tmux-plugins/tmux-resurrect
## Followup Items
# https://github.com/ghostty-org/ghostty/issues/4538
# Update vault-keyring-client.py to work on linux/docker by alternativly getting user input, or taking a var
# Put vault-keyring-client.py into a module so it can be used by many repos
# https://wiki.archlinux.org/title/XDG_Base_Directory
# Use https://github.com/b3nj5m1n/xdg-ninja to aid clearing out ~/
# 

#https://macos-defaults.com/
- name: MacOS Playbook
  hosts: "localhost"
  roles:
  #- role: asdf
  # TODO can't find a working version so need to build a role
  - role: staticdev.pyenv
  #- to do https://github.com/staticdev/ansible-role-pyenv/blob/main/tasks/install.yml 
  #  fork and remove the install stuff? Or don't use brew to install it

  tasks:
    - name: "Set macOS default settings (privlaged)"
      community.general.osx_defaults:
        domain: "{{ item['domain'] }}"
        key: "{{ item['key'] }}"
        type: "{{ item['type'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ system_macos_defaults }}"
      loop_control:
        label: "{{ item['name'] }}"
      become: true
      #notify: Restart macOS dock
    - name: "Set macOS default settings (user)"
      community.general.osx_defaults:
        domain: "{{ item['domain'] }}"
        key: "{{ item['key'] }}"
        type: "{{ item['type'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ user_macos_defaults }}"
      loop_control:
        label: "{{ item['name'] }}"
      become: false
      #notify: Restart macOS dock