---

#   ^#\s+(.*?)\ndefaults write (\S+)\s+(\S+)\s+-(\S+)\s(.*?)$
#   - domain: $2\n  key: $3\n  type: $4\n  value: $5\n  name: $1\n

#https://macos-defaults.com/
- name: MacOS Playbook
  hosts: "localhost"
  roles:
  #- role: asdf
  # TODO can't find a working version so need to build a role
  - role: staticdev.pyenv
  #- to do https://github.com/staticdev/ansible-role-pyenv/blob/main/tasks/install.yml 
  #  fork and remove the install stuff? Or don't use brew to install it

  tasks:
    - name: "Set macOS default settings (privlaged)"
      community.general.osx_defaults:
        domain: "{{ item['domain'] }}"
        key: "{{ item['key'] }}"
        type: "{{ item['type'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ system_macos_defaults }}"
      loop_control:
        label: "{{ item['name'] }}"
      become: true
      #notify: Restart macOS dock
    - name: "Set macOS default settings (user)"
      community.general.osx_defaults:
        domain: "{{ item['domain'] }}"
        key: "{{ item['key'] }}"
        type: "{{ item['type'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ user_macos_defaults }}"
      loop_control:
        label: "{{ item['name'] }}"
      become: false
      #notify: Restart macOS dock